### ISSUE TITLE
Failed to compile `SwiftFoundation/Thread.swift`.

### ISSUE THREAD

**Issue by weakish** [PureSwift/SwiftFoundation#34]
On `713b3ce`:

First,  not found `CUUID`.

```
SwiftFoundation/Sources/SwiftFoundation/UUID.swift:14:12: error: no such module 'CUUID'
    import CUUID
           ^
```

Edited `Package.swift` fixing the above error:

``` patch
--- a/Package.swift
+++ b/Package.swift
@@ -11,7 +11,8 @@ let package = Package(
     ],
     dependencies: [
         .Package(url: "https://github.com/PureSwift/CStatfs.git", majorVersion: 1),
-        .Package(url: "https://github.com/PureSwift/CJSONC.git", majorVersion: 1)
+        .Package(url: "https://github.com/PureSwift/CJSONC.git", majorVersion: 1),
+        .Package(url: "https://github.com/PureSwift/CUUID.git", majorVersion: 1)
     ],
     exclude: ["Xcode", "Carthage"]
 )
```

Then failed to compile `SwiftFoundation/Thread.swift`:

``
src/SwiftFoundation/Sources/SwiftFoundation/Thread.swift:30:54: error: va$
ue of type 'Unmanaged<Thread.Closure>' has no member 'toOpaque'
            let pointer = UnsafeMutablePointer<Void>(holder.toOpaque())
                                                     ^~~~~~ ~~~~~~~~
src/SwiftFoundation/Sources/SwiftFoundation/Thread.swift:89:65: error: ca$
not convert value of type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePoint$
r<()>') to expected argument type 'OpaquePointer'
        let unmanaged = Unmanaged<Thread.Closure>.fromOpaque(arg!)
                                                             ~~~^

```
```

**Comment by colemancda** [comment]
Don't use the development snapshot, compile the latest Swift version. Now CUUID is part of the Glibc module map.
