### ISSUE TITLE
base64 tests

### ISSUE THREAD

**Issue by drichardson** [PureSwift/SwiftFoundation#4]
For base64 tests you might want to include the ones here in addition to the tests you already have:
https://github.com/drichardson/SwiftyBase64/blob/master/SwiftyBase64Tests/SwiftyBase64Tests.swift
since they specifically cover different cases the base64 encoder has to handle (thanks for the header attribution, btw).

Also, I think an open source, cross platform, pure swift replacement for Foundation is a great idea.

**Comment by colemancda** [comment]
thanks @drichardson I'll look into it. Thanks again for your pure swift algorithm. If you write a decoding one I wouldn't need libb64 as a dependency :)

**Comment by colemancda** [comment]
Sorry, but I removed all Swift Base64 algorithms, we rely on a C library now.
@drichardson

**Comment by drichardson** [comment]
Going to rename group to TaintedSwift? ;)

**Comment by colemancda** [comment]
@drichardson Lol, we don't have any Objective-C code, that is the focus. We more than welcome C code, however.
