### ISSUE TITLE
Compilation under Windows

### ISSUE THREAD

**Issue by Blackjacx** [PureSwift/SwiftFoundation#40]
Hey,

this is not really an issue but more a feature. I want to implement a cross platform (macos, iOS, Windows, Linux) tool and need some JSON de-serialization and file management. Currently I think about which library I want to use. My main question is if it is generally possible to compile Swift foundation under Windows since the OS is not listed in your readme.

**Comment by colemancda** [comment]
I have never tried it, and dont use PCs. But you are welcome to try it.

**Comment by Blackjacx** [comment]
I will when it is time :-)
