### ISSUE TITLE
Be more modular

### ISSUE THREAD

**Issue by Danappelxx** [PureSwift/SwiftFoundation#8]
I'm looking for a good foundation-free JSON serializer and came upon PureSwift's, which has the barebones - exactly what I need. However, including the entire SwiftFoundation project is overkill if I just want JSON.

I propose to split all the large sections into separate repositories, and then this repository would just be the core that links them together and conforms the types to the necessary (probably `FoundationConvertible`) protocols. This might be a pain to do right now, but in the long run it's a much better solution.

**Comment by colemancda** [comment]
Hmm, good idea. I'll have to put a lot of thought into this, but I'll definitely consider it. In the meanwhile, you are more than free to "steal" my code (its MIT Licensed). If you do, put it in a repo and send me a link :)

**Comment by colemancda** [comment]
@Danappelxx I took a look at your SwiftMongoDB project. If you integrated SwiftFoundation, or just stole the JSON code, I could see safety and performance benefits. Also, I'd really appreciate it if you make your project Linux compatible, I would then be able to use it and contribute to it.

**Comment by Danappelxx** [comment]
Great! I'll try to integrate SwiftFoundation asap, but unfortunately I'm going to be offline for most of this thanksgiving break. I've narrowed down the foundation dependency to two domains (JSON and dictionary comparison), so I'm very close. If you're up for it - I'll definitely take a pr!

**Comment by colemancda** [comment]
Separated JSON and Base64 into separate repos (see #17). Fixed as of v1.1.0.
